INSERT INTO gravadora ( nome_gravadora, pais) VALUES ( 'Sony', 'Estados Unidos');
INSERT INTO gravadora ( nome_gravadora, pais) VALUES ( 'Som livre', 'Brasil');
INSERT INTO gravadora ( nome_gravadora, pais) VALUES ( 'EMI', 'Estados Unidos');
INSERT INTO gravadora ( nome_gravadora, pais) VALUES ( 'Globo', 'Brasil');
INSERT INTO gravadora ( nome_gravadora, pais) VALUES ( 'Trama', 'Brasil');
INSERT INTO gravadora ( nome_gravadora, pais) VALUES ( 'ACIT', 'Brasil');

INSERT INTO cantor ( nome_cantor, pais) VALUES ( 'Marisa Monte', 'Brasil');
INSERT INTO cantor ( nome_cantor, pais) VALUES ( 'Coldplay', 'Inglaterra');
INSERT INTO cantor ( nome_cantor, pais) VALUES ( 'U2', 'Irlanda');
INSERT INTO cantor ( nome_cantor, pais) VALUES ( 'Djavan', 'Brasil');
INSERT INTO cantor ( nome_cantor, pais) VALUES ( 'Laura Pausini', 'Italia');
INSERT INTO cantor ( nome_cantor, pais) VALUES ( 'Roberto Leal', 'Portugal');
INSERT INTO cantor ( nome_cantor, pais) VALUES ( 'The Corrs', 'Estados Unidos');
INSERT INTO cantor ( nome_cantor, pais) VALUES ( 'Legiao Urbana', 'Brasil');
INSERT INTO cantor ( nome_cantor, pais) VALUES ( 'Cazuza', 'Brasil');
INSERT INTO cantor ( nome_cantor, pais) VALUES ( 'Tom Jobim', 'Brasil');
INSERT INTO cantor ( nome_cantor, pais) VALUES ( 'Frank Sinatra', 'Estados Unidos');
INSERT INTO cantor ( nome_cantor, pais) VALUES ( 'Porca Véia', 'Brasil');

INSERT INTO categoria (desc_categoria) VALUES ( 'MPB');
INSERT INTO categoria (desc_categoria) VALUES ( 'Rock');
INSERT INTO categoria (desc_categoria) VALUES ( 'Vira');
INSERT INTO categoria (desc_categoria) VALUES ( 'Bossa Nova');
INSERT INTO categoria (desc_categoria) VALUES ( 'Jazz');
INSERT INTO categoria (desc_categoria) VALUES ( 'Pop rock');
INSERT INTO categoria (desc_categoria) VALUES ( 'Eletronic');
INSERT INTO categoria (desc_categoria) VALUES ( 'Pop');
INSERT INTO categoria (desc_categoria) VALUES ( 'Gaucha');

INSERT INTO musica (cod_categoria, duracao, titulo) VALUES ( 1, 240, 'Amor I love you');
INSERT INTO musica (cod_categoria, duracao, titulo) VALUES ( 1, 300, 'Nao e facil');
INSERT INTO musica (cod_categoria, duracao, titulo) VALUES ( 1, 250, 'Gentileza');
INSERT INTO musica (cod_categoria, duracao, titulo) VALUES ( 2, 500, 'Daniel na cova dos leoes');
INSERT INTO musica (cod_categoria, duracao, titulo) VALUES ( 2, 322, 'Fabrica');
INSERT INTO musica (cod_categoria, duracao, titulo) VALUES ( 2, 440, 'Tempo perdido');
INSERT INTO musica (cod_categoria, duracao, titulo) VALUES ( 2, 312, 'Acrilic on canvas');
INSERT INTO musica (cod_categoria, duracao, titulo) VALUES ( 3, 298, 'Vira-vira');
INSERT INTO musica (cod_categoria, duracao, titulo) VALUES ( 4, 348, 'Chega de saudade');
INSERT INTO musica (cod_categoria, duracao, titulo) VALUES ( 4, 231, 'Luiza');
INSERT INTO musica (cod_categoria, duracao, titulo) VALUES ( 4, 355, 'Aguas de marco');
INSERT INTO musica (cod_categoria, duracao, titulo) VALUES ( 4, 250, 'Wave');
INSERT INTO musica (cod_categoria, duracao, titulo) VALUES ( 6, 333, 'Politik');
INSERT INTO musica (cod_categoria, duracao, titulo) VALUES ( 6, 225, 'Green eyes');
INSERT INTO musica (cod_categoria, duracao, titulo) VALUES ( 6, 440, 'A Rush of Blood to the head');
INSERT INTO musica (cod_categoria, duracao, titulo) VALUES ( 6, 320, 'Clocks');
INSERT INTO musica (cod_categoria, duracao, titulo) VALUES ( 6, 300, 'Codinome beija-flor');
INSERT INTO musica (cod_categoria, duracao, titulo) VALUES ( 6, 290, 'Faz parte do meu show');
INSERT INTO musica (cod_categoria, duracao, titulo) VALUES ( 5, 446, 'New York');
INSERT INTO musica (cod_categoria, duracao, titulo) VALUES ( 8, 299, 'Solitudine');
INSERT INTO musica (cod_categoria, duracao, titulo) VALUES ( 1, 430, 'Oceano');
INSERT INTO musica (cod_categoria, duracao, titulo) VALUES ( 2, 511, 'With or without you');
INSERT INTO musica (cod_categoria, duracao, titulo) VALUES ( 2, 300, 'Beautiful day');
INSERT INTO musica (cod_categoria, duracao, titulo) VALUES ( 2, 458, 'Bullet The Blue Sky');
INSERT INTO musica (cod_categoria, duracao, titulo) VALUES ( 1, 300, 'Sua');
INSERT INTO musica (cod_categoria, duracao, titulo) VALUES ( 9, 255, 'Luz do meu rancho');
