INSERT INTO gravadora ( nome_gravadora, pais) VALUES ( 'Sony', 'Estados Unidos');
INSERT INTO gravadora ( nome_gravadora, pais) VALUES ( 'Som livre', 'Brasil');
INSERT INTO gravadora ( nome_gravadora, pais) VALUES ( 'EMI', 'Estados Unidos');
INSERT INTO gravadora ( nome_gravadora, pais) VALUES ( 'Globo', 'Brasil');
INSERT INTO gravadora ( nome_gravadora, pais) VALUES ( 'Trama', 'Brasil');
INSERT INTO gravadora ( nome_gravadora, pais) VALUES ( 'ACIT', 'Brasil');

INSERT INTO cantor ( nome_cantor, pais) VALUES ( 'Marisa Monte', 'Brasil');
INSERT INTO cantor ( nome_cantor, pais) VALUES ( 'Coldplay', 'Inglaterra');
INSERT INTO cantor ( nome_cantor, pais) VALUES ( 'U2', 'Irlanda');
INSERT INTO cantor ( nome_cantor, pais) VALUES ( 'Djavan', 'Brasil');
INSERT INTO cantor ( nome_cantor, pais) VALUES ( 'Laura Pausini', 'Italia');
INSERT INTO cantor ( nome_cantor, pais) VALUES ( 'Roberto Leal', 'Portugal');
INSERT INTO cantor ( nome_cantor, pais) VALUES ( 'The Corrs', 'Estados Unidos');
INSERT INTO cantor ( nome_cantor, pais) VALUES ( 'Legiao Urbana', 'Brasil');
INSERT INTO cantor ( nome_cantor, pais) VALUES ( 'Cazuza', 'Brasil');
INSERT INTO cantor ( nome_cantor, pais) VALUES ( 'Tom Jobim', 'Brasil');
INSERT INTO cantor ( nome_cantor, pais) VALUES ( 'Frank Sinatra', 'Estados Unidos');
INSERT INTO cantor ( nome_cantor, pais) VALUES ( 'Porca Véia', 'Brasil');

INSERT INTO categoria (desc_categoria) VALUES ( 'MPB');
INSERT INTO categoria (desc_categoria) VALUES ( 'Rock');
INSERT INTO categoria (desc_categoria) VALUES ( 'Vira');
INSERT INTO categoria (desc_categoria) VALUES ( 'Bossa Nova');
INSERT INTO categoria (desc_categoria) VALUES ( 'Jazz');
INSERT INTO categoria (desc_categoria) VALUES ( 'Pop rock');
INSERT INTO categoria (desc_categoria) VALUES ( 'Eletronic');
INSERT INTO categoria (desc_categoria) VALUES ( 'Pop');
INSERT INTO categoria (desc_categoria) VALUES ( 'Gaucha');

INSERT INTO musica (cod_categoria, duracao, titulo) VALUES ( 1, 240, 'Amor I love you');
INSERT INTO musica (cod_categoria, duracao, titulo) VALUES ( 1, 300, 'Nao e facil');
INSERT INTO musica (cod_categoria, duracao, titulo) VALUES ( 1, 250, 'Gentileza');
INSERT INTO musica (cod_categoria, duracao, titulo) VALUES ( 2, 500, 'Daniel na cova dos leoes');
INSERT INTO musica (cod_categoria, duracao, titulo) VALUES ( 2, 322, 'Fabrica');
INSERT INTO musica (cod_categoria, duracao, titulo) VALUES ( 2, 440, 'Tempo perdido');
INSERT INTO musica (cod_categoria, duracao, titulo) VALUES ( 2, 312, 'Acrilic on canvas');
INSERT INTO musica (cod_categoria, duracao, titulo) VALUES ( 3, 298, 'Vira-vira');
INSERT INTO musica (cod_categoria, duracao, titulo) VALUES ( 4, 348, 'Chega de saudade');
INSERT INTO musica (cod_categoria, duracao, titulo) VALUES ( 4, 231, 'Luiza');
INSERT INTO musica (cod_categoria, duracao, titulo) VALUES ( 4, 355, 'Aguas de marco');
INSERT INTO musica (cod_categoria, duracao, titulo) VALUES ( 4, 250, 'Wave');
INSERT INTO musica (cod_categoria, duracao, titulo) VALUES ( 6, 333, 'Politik');
INSERT INTO musica (cod_categoria, duracao, titulo) VALUES ( 6, 225, 'Green eyes');
INSERT INTO musica (cod_categoria, duracao, titulo) VALUES ( 6, 440, 'A Rush of Blood to the head');
INSERT INTO musica (cod_categoria, duracao, titulo) VALUES ( 6, 320, 'Clocks');
INSERT INTO musica (cod_categoria, duracao, titulo) VALUES ( 6, 300, 'Codinome beija-flor');
INSERT INTO musica (cod_categoria, duracao, titulo) VALUES ( 6, 290, 'Faz parte do meu show');
INSERT INTO musica (cod_categoria, duracao, titulo) VALUES ( 5, 446, 'New York');
INSERT INTO musica (cod_categoria, duracao, titulo) VALUES ( 8, 299, 'Solitudine');
INSERT INTO musica (cod_categoria, duracao, titulo) VALUES ( 1, 430, 'Oceano');
INSERT INTO musica (cod_categoria, duracao, titulo) VALUES ( 2, 511, 'With or without you');
INSERT INTO musica (cod_categoria, duracao, titulo) VALUES ( 2, 300, 'Beautiful day');
INSERT INTO musica (cod_categoria, duracao, titulo) VALUES ( 2, 458, 'Bullet The Blue Sky');
INSERT INTO musica (cod_categoria, duracao, titulo) VALUES ( 1, 300, 'Sua');
INSERT INTO musica (cod_categoria, duracao, titulo) VALUES ( 9, 255, 'Luz do meu rancho');

INSERT INTO gravacao (cod_gravacao, cod_gravadora, cod_cantor, cod_musica, data_gravacao) VALUES (1, 1, 1, 1, '2000-07-10');
INSERT INTO gravacao (cod_gravacao, cod_gravadora, cod_cantor, cod_musica, data_gravacao) VALUES (2, 1, 1, 2, '2000-12-07');
INSERT INTO gravacao (cod_gravacao, cod_gravadora, cod_cantor, cod_musica, data_gravacao) VALUES (3, 1, 1, 3, '2001-05-30');
INSERT INTO gravacao (cod_gravacao, cod_gravadora, cod_cantor, cod_musica, data_gravacao) VALUES (4, 3, 8, 4, '2005-12-29');
INSERT INTO gravacao (cod_gravacao, cod_gravadora, cod_cantor, cod_musica, data_gravacao) VALUES (5, 3, 8, 5, '1993-04-25');
INSERT INTO gravacao (cod_gravacao, cod_gravadora, cod_cantor, cod_musica, data_gravacao) VALUES (6, 3, 8, 6, '1989-01-31');
INSERT INTO gravacao (cod_gravacao, cod_gravadora, cod_cantor, cod_musica, data_gravacao) VALUES (7, 3, 8, 7, '1991-12-01');
INSERT INTO gravacao (cod_gravacao, cod_gravadora, cod_cantor, cod_musica, data_gravacao) VALUES (8, 3, 6, 8, '1988-07-30');
INSERT INTO gravacao (cod_gravacao, cod_gravadora, cod_cantor, cod_musica, data_gravacao) VALUES (9, 4, 10, 9, '1978-10-14');
INSERT INTO gravacao (cod_gravacao, cod_gravadora, cod_cantor, cod_musica, data_gravacao) VALUES (10, 4, 10, 10, '1975-08-11');
INSERT INTO gravacao (cod_gravacao, cod_gravadora, cod_cantor, cod_musica, data_gravacao) VALUES (11, 4, 10, 11, '1979-05-05');
INSERT INTO gravacao (cod_gravacao, cod_gravadora, cod_cantor, cod_musica, data_gravacao) VALUES (12, 4, 10, 12, '1981-04-18');
INSERT INTO gravacao (cod_gravacao, cod_gravadora, cod_cantor, cod_musica, data_gravacao) VALUES (13, 1, 2, 13, '2004-09-12');
INSERT INTO gravacao (cod_gravacao, cod_gravadora, cod_cantor, cod_musica, data_gravacao) VALUES (14, 1, 2, 14, '2004-09-20');
INSERT INTO gravacao (cod_gravacao, cod_gravadora, cod_cantor, cod_musica, data_gravacao) VALUES (16, 1, 2, 16, '2004-10-01');
INSERT INTO gravacao (cod_gravacao, cod_gravadora, cod_cantor, cod_musica, data_gravacao) VALUES (17, 4, 9, 17, '1986-06-30');
INSERT INTO gravacao (cod_gravacao, cod_gravadora, cod_cantor, cod_musica, data_gravacao) VALUES (18, 5, 9, 18, '1987-07-06');
INSERT INTO gravacao (cod_gravacao, cod_gravadora, cod_cantor, cod_musica, data_gravacao) VALUES (19, 1, 11, 19, '1971-08-29');
INSERT INTO gravacao (cod_gravacao, cod_gravadora, cod_cantor, cod_musica, data_gravacao) VALUES (20, 3, 5, 20, '1998-10-10');
INSERT INTO gravacao (cod_gravacao, cod_gravadora, cod_cantor, cod_musica, data_gravacao) VALUES (21, 5, 4, 21, '1995-01-20');
INSERT INTO gravacao (cod_gravacao, cod_gravadora, cod_cantor, cod_musica, data_gravacao) VALUES (22, 1, 3, 22, '1989-05-05');
INSERT INTO gravacao (cod_gravacao, cod_gravadora, cod_cantor, cod_musica, data_gravacao) VALUES (23, 1, 3, 23, '1991-10-20');
INSERT INTO gravacao (cod_gravacao, cod_gravadora, cod_cantor, cod_musica, data_gravacao) VALUES (24, 1, 3, 24, '1992-03-25');
INSERT INTO gravacao (cod_gravacao, cod_gravadora, cod_cantor, cod_musica, data_gravacao) VALUES (25, 5, 1, 25, '1998-10-20');
INSERT INTO gravacao (cod_gravacao, cod_gravadora, cod_cantor, cod_musica, data_gravacao) VALUES (15, 1, 2, 15, '2004-08-30');